# Osaka Jade Theme
THEME_NAME="Osaka Jade"
BG="#111c18"
BG_ALT="#23372B"
FG="#C1C497"
FG_DIM="#53685B"
ACCENT="#509475"
ACCENT2="#D2689C"
SELECTION_FG="#111C18"
SELECTION_BG="#C1C497"
CURSOR="#D7C995"
RED="#FF5345"
GREEN="#549e6a"
YELLOW="#459451"
BLUE="#509475"
MAGENTA="#D2689C"
CYAN="#2DD5B7"
WHITE="#F6F5DD"
BLACK="#23372B"
BRIGHT_BLACK="#53685B"
GTK_THEME="Adwaita-dark"
ICON_THEME="Adwaita"
