# Autostart
exec-once = waybar
exec-once = swaync
exec-once = swaybg -m fill -i ~/.config/omarchy/current/wallpaper
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = hypridle
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# SwayOSD (if installed)
exec-once = swayosd-server || true
