# Autostart
exec-once = waybar
exec-once = swaync
exec-once = swww-daemon
exec-once = sleep 0.5 && swww img ~/.config/omarchy/current/wallpaper --transition-type fade --transition-duration 1
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = hypridle
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# Hyprland plugins (recompile if needed on session start)
exec-once = hyprpm reload -n

# SwayOSD (if installed)
exec-once = swayosd-server || true
