# Miasma Theme
THEME_NAME="Miasma"
BG="#222222"
BG_ALT="#000000"
FG="#c2c2b0"
FG_DIM="#666666"
ACCENT="#78824b"
ACCENT2="#bb7744"
SELECTION_FG="#c2c2b0"
SELECTION_BG="#78824b"
CURSOR="#c7c7c7"
RED="#685742"
GREEN="#5f875f"
YELLOW="#b36d43"
BLUE="#78824b"
MAGENTA="#bb7744"
CYAN="#c9a554"
WHITE="#d7c483"
BLACK="#000000"
BRIGHT_BLACK="#666666"
GTK_THEME="Adwaita-dark"
ICON_THEME="Adwaita"
