#* Color theme
color_theme = "tokyo-night"

#* Use rounded corners
rounded_corners = True

#* Default shown graph
shown_boxes = "cpu mem net proc"

#* Update time in milliseconds
update_ms = 1000

#* Use vim keys
vim_keys = True

#* Show battery stats
show_battery = True
