# Matte Black Theme
THEME_NAME="Matte Black"
BG="#121212"
BG_ALT="#333333"
FG="#bebebe"
FG_DIM="#8a8a8d"
ACCENT="#e68e0d"
ACCENT2="#D35F5F"
SELECTION_FG="#bebebe"
SELECTION_BG="#333333"
CURSOR="#eaeaea"
RED="#D35F5F"
GREEN="#FFC107"
YELLOW="#b91c1c"
BLUE="#e68e0d"
MAGENTA="#D35F5F"
CYAN="#bebebe"
WHITE="#bebebe"
BLACK="#333333"
BRIGHT_BLACK="#8a8a8d"
GTK_THEME="Adwaita-dark"
ICON_THEME="Adwaita"
