# Hackerman Theme
THEME_NAME="Hackerman"
BG="#0B0C16"
BG_ALT="#0B0C16"
FG="#ddf7ff"
FG_DIM="#6a6e95"
ACCENT="#82FB9C"
ACCENT2="#86a7df"
SELECTION_FG="#0B0C16"
SELECTION_BG="#ddf7ff"
CURSOR="#ddf7ff"
RED="#50f872"
GREEN="#4fe88f"
YELLOW="#50f7d4"
BLUE="#829dd4"
MAGENTA="#86a7df"
CYAN="#7cf8f7"
WHITE="#85E1FB"
BLACK="#0B0C16"
BRIGHT_BLACK="#6a6e95"
GTK_THEME="Adwaita-dark"
ICON_THEME="Adwaita"
