# Vantablack Theme
THEME_NAME="Vantablack"
BG="#0d0d0d"
BG_ALT="#0d0d0d"
FG="#ffffff"
FG_DIM="#fdfdfd"
ACCENT="#8d8d8d"
ACCENT2="#9b9b9b"
SELECTION_FG="#0d0d0d"
SELECTION_BG="#ffffff"
CURSOR="#ffffff"
RED="#a4a4a4"
GREEN="#b6b6b6"
YELLOW="#cecece"
BLUE="#8d8d8d"
MAGENTA="#9b9b9b"
CYAN="#b0b0b0"
WHITE="#ececec"
BLACK="#0d0d0d"
BRIGHT_BLACK="#fdfdfd"
GTK_THEME="Adwaita-dark"
ICON_THEME="Adwaita"
