# Ethereal Theme
THEME_NAME="Ethereal"
BG="#060B1E"
BG_ALT="#060B1E"
FG="#ffcead"
FG_DIM="#6d7db6"
ACCENT="#7d82d9"
ACCENT2="#c89dc1"
SELECTION_FG="#060B1E"
SELECTION_BG="#ffcead"
CURSOR="#ffcead"
RED="#ED5B5A"
GREEN="#92a593"
YELLOW="#E9BB4F"
BLUE="#7d82d9"
MAGENTA="#c89dc1"
CYAN="#a3bfd1"
WHITE="#F99957"
BLACK="#060B1E"
BRIGHT_BLACK="#6d7db6"
GTK_THEME="Adwaita-dark"
ICON_THEME="Adwaita"
